services:
  - type: web
    name: cafeteria-backend
    runtime: docker
    plan: starter
    region: ohio

    # Ruta al Dockerfile contando desde la ra√≠z del repo
    dockerfilePath: backend/Dockerfile

    envVars:
      - key: DATABASE_URL
        sync: false   # la configuras en el panel de Render
      - key: JWT_SECRET
        sync: false   # la configuras en el panel de Render
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
